apiVersion: v1
kind: Service
metadata:
  name: practica-cicd-service
  namespace: default          # Opcional, Flux aplicará el targetNamespace si no está definido
spec:
  selector:
    app: practica-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007         # Si usas NodePort para exponer externamente
  type: NodePort
