version: 2.1

jobs:
  # Job: Construcción de la imagen Docker
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker   # Habilita Docker remoto para este job
      - run:
          name: Instalar dependencias de la aplicación
          command: pip install -r requirements.txt
      - run:
          name: Construir la imagen Docker
          command: docker build -t dias-vividos-cli .
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Job: Ejecutar pruebas y generar reporte de cobertura
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Instalar dependencias de prueba
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-cov
      - run:
          name: Ejecutar pruebas con cobertura
          command: pytest --cov=. --cov-report xml
      - store_artifacts:
          path: coverage.xml
          destination: coverage

  # Job: Linting con Flake8
  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Instalar Flake8
          command: pip install flake8
      - run:
          name: Ejecutar linting
          command: flake8 .

  # Job: Análisis estático con Bandit
  static_analysis:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Instalar Bandit
          command: pip install bandit
      - run:
          name: Ejecutar análisis estático
          command: bandit -r .

  # Job: Análisis de código y vulnerabilidades con SonarQube
  sonar_scan:
    docker:
      - image: cimg/openjdk:17.0.2-slim  # Usamos Java 17
    steps:
      - checkout
      - run:
          name: Instalar herramientas (wget y unzip)
          command: |
            sudo apt-get update && sudo apt-get install -y wget unzip
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: Descargar e instalar SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
            unzip sonar-scanner-cli-4.8.0.2856-linux.zip
            ./sonar-scanner-4.8.0.2856-linux/bin/sonar-sc
