apiVersion: v1
kind: Service
metadata:
  name: practica-cicd-service
  namespace: default
spec:
  selector:
    app: practica-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000   # Asegúrate de apuntar al puerto 5000, donde Flask está escuchando
      nodePort: 30007
  type: NodePort
