apiVersion: apps/v1
kind: Deployment
metadata:
  name: dias-vividos-cli
  namespace: default
  labels:
    app: dias-vividos-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dias-vividos-cli
  template:
    metadata:
      labels:
        app: dias-vividos-cli
    spec:
      automountServiceAccountToken: false   # 🛡️ Seguridad
      containers:
      - name: dias-vividos-cli
        image: guillermors28/dias-vividos-cli:latest
        ports:
        - containerPort: 5000
        resources:                          # 📦 Control de recursos
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
