apiVersion: v1
kind: Service
metadata:
  name: practica-cicd-service
  namespace: default         # Añadir el namespace aquí
spec:
  selector:
    app: practica-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007         # Si usas NodePort
  type: NodePort
